baseurl = "https://portfolio.geekhomeinside.io/"
languageCode = "en-us"
theme = "hugo-theme-terminal"
paginate = 5

[params]
  contentTypeName = "post"
  themeColor = "green"
  showMenuItems = 2
  fullWidthTheme = true
  centerTheme = true

[languages]
  [languages.en]
    title = "GeekHomeInside"
    subtitle = "Portfolio"
    keywords = "portfolio, tutorial, gitlab, github, linkedin"
    copyright = ""
    menuMore = "Show more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "GeekHomeInside"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"